Repository FromDoppler/doppler-sap, pull requests merged in 2024-10, with the labels that each got.

#338 [DAT-2201] - Add new conversation plans
  Doppler.Sap/Resources/SapBillingItems.json
Labels: size/XS

#339 [DAT-2209] - Send custom plan to sap
  Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
  Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
  Doppler.Sap/Models/AdditionalServiceModel.cs
Labels: size/M

#340 [DAT-2222] Add new plan info
  Doppler.Sap/Resources/SapBillingItems.json
Labels: size/XS

#341 [DAT-2224] - Add userid in the freetext when the user is a cm
  Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
  Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
  Doppler.Sap/Models/AdditionalServiceModel.cs
Labels: size/S

#342 [DAT-2224] - Add user id for the landing plans for the cm users
  Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
  Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Labels: size/S

#343 [DAT-2224] - Show email in the free text
  Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
  Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
  Doppler.Sap/Models/AdditionalServiceModel.cs
Labels: size/S
